[package]
name = "zenith-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck.workspace  = true
log.workspace = true
anyhow.workspace = true

zenith-rhi = { path = "../zenith-rhi" }
zenith-rendergraph = { path = "../zenith-rendergraph" }